project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Soil 2125 Laboratory Manual - pdf edition"
  author: "Nic Jelinski"
  date: "22DEC2022"
  chapters:
    - index.qmd
    - laboratory-1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    classoption: [twocolumn, portrait]
    fontfamily: libertinus
    geometry:
      - top=25.4mm
      - bottom=30mm
      - left=25.4mm
      - right=25.4mm
      - heightrounded
    toc: true
    number-sections: true
    number-depth: 3
    colorlinks: true
    pagestyle: headings

editor: visual